### ISSUE TITLE
Feature request: sending user notification count to calling app

### ISSUE THREAD

**Issue by sylque** [sylque/dcs-discourse-plugin#4]
This would be nice to have for enriching the calling app UI.

**Comment by sylque** [comment]
@AndyatFocallocal, I confirm this can be done and will be implemented in next version.

**Comment by sylque** [comment]
Fixed in 1.0.2.

**Comment by AndyatFocallocal** [comment]
this was the issue which added the ability for the balloons on the map to display the number of threads in discourse, wasn't it @sylque?

did this also allow us to add some code to the profile icon in the main menu? or is that still to come? we should add an issue for it here if the latter

**Comment by sylque** [comment]
@AndyatFocallocal, I've just sent you a private message to summarize where we stand with feature requests.
